### ISSUE TITLE
asami-loom compatibility with asami

### ISSUE THREAD

**Issue by mdallastella** [threatgrid/asami-loom#1]
Hi,

### Environment
Clojure 1.10.3, Asami 1.2.16, Asami-loom 0.2.0

### Problem

I was taking a look at asami-loom, following the example on the [README.md](https://github.com/threatgrid/asami-loom#example), but it fails at the following steps:

1. Define `node-label`
```clojure
user> (defn node-label
        [g n]
        (let [id (q [:find '?id . :where [n :db/ident '?id]] g)]
          (cond id (str id)
                (and (keyword? n) (= (namespace n) "tg")) (str ":" (name n))
                :default (str n))))
Syntax error compiling at (*cider-repl 7b:localhost:42129(clj)*:35:18).
Unable to resolve symbol: . in this context
```

2. Require `asami-loom.index`
```clojure
user> (require '[asami-loom.index])
Syntax error (IllegalArgumentException) compiling graph-add at (asami_loom/index.cljc:63:35).
No single method: graph_add of interface: asami.graph.Graph found for function: graph-add of protocol: Graph
```

3. Require `asami-loom.label`
```clojure
user> (require '[asami-loom.label])
Syntax error (IllegalArgumentException) compiling graph-add at (asami_loom/label.cljc:18:7).
No single method: graph_add of interface: asami.graph.Graph found for function: graph-add of protocol: Graph
```

Thanks,
Marco

**Comment by quoll** [comment]
A new [Asami2](https://github.com/threatgrid/asami-loom/tree/asami2) branch is now working with the latest undeployed Asami 2.0.0 alpha (in the ["transitive" branch](https://github.com/threatgrid/asami/tree/transitive)).

The next Asami should be out in the next few days, at which point this branch can be merged into `main` and deployed.

**Comment by quoll** [comment]
> 1. Define `node-label`
> 
> ```clojure
> user> (defn node-label
>         [g n]
>         (let [id (q [:find '?id . :where [n :db/ident '?id]] g)]
>           (cond id (str id)
>                 (and (keyword? n) (= (namespace n) "tg")) (str ":" (name n))
>                 :default (str n))))
> Syntax error compiling at (*cider-repl 7b:localhost:42129(clj)*:35:18).
> Unable to resolve symbol: . in this context
> ```

The query here needs to be corrected:
`(q [:find '?id . :where [n :db/ident '?id]] g)`

The Clojure reader fails on the unquoted `.` symbol since it is not bound to anything. Since you have the value `n` you can handle this in a variety of ways:
`(q [:find '?id '. :where [n :db/ident '?id]] g)`
`(q '[:find ?id . :in $ ?n :where [?n :db/ident ?id]] g n)`
`(q {:find '[?id .] :where [[n :db/ident '?id]]} g)`

You could even make a definition that would leave your original line alone:
```clojure
(def . '.)
(q [:find '?id . :where [n :db/ident '?id]] g)
```
But that's probably going overboard 🙂

**Comment by quoll** [comment]
OK... I see that the query was from the README. My apologies.

The README has been updated with code that is tested, and the 0.3.1 release has all the new API changes.
